
/**
 ******************************************************************************
 * @file           : stm32f411xx.h
 * @author         : Auto-generated by drmahnal
 * @brief          : Register of MCU
 ******************************************************************************
 */
#ifndef INC_STM32F411XX_H_
#define INC_STM32F411XX_H_

/*
 * base addresses of flash and SRAM memories
 *
 */
#define FLASH_BASEADDR
#define SRAM1_BASEADDR
#define SRMA2_BASEADDR
#define ROM
#define SRAM


#endif
